{{- if not .Values.cloudControllerManager.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "binarylane-cloud-controller-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "binarylane-cloud-controller-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ required "cloudControllerManager.apiToken is required when existingSecret is not set" .Values.cloudControllerManager.apiToken | quote }}
{{- end }}
