{{- if .Values.createTestSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudControllerManager.secret.name | default "binarylane-api-token" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "binarylane-cloud-controller-manager.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.cloudControllerManager.secret.key }}: "test-token-for-ci"
{{- end }}
