apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarylane-cloud-controller-manager
  namespace: kube-system
  labels:
    app: binarylane-cloud-controller-manager
spec:
  replicas: 1 # Adjust the number of replicas as needed
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: binarylane-cloud-controller-manager
  template:
    metadata:
      labels:
        app: binarylane-cloud-controller-manager
    spec:
      dnsPolicy: Default
      hostNetwork: true
      serviceAccountName: cloud-controller-manager
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: binarylane-cloud-controller-manager
      tolerations:
        - key: 'node.cloudprovider.kubernetes.io/uninitialized'
          value: 'true'
          effect: 'NoSchedule'
        - key: 'CriticalAddonsOnly'
          operator: 'Exists'
        - key: 'node-role.kubernetes.io/master'
          effect: NoSchedule
        - key: 'node-role.kubernetes.io/control-plane'
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
      containers:
        - name: binarylane-cloud-controller-manager
          image: ghcr.io/oscarhermoso/binarylane-cloud-controller-manager:latest
          imagePullPolicy: IfNotPresent
          command:
            - '/binarylane-cloud-controller-manager'
            - '--cloud-provider=binarylane'
            - '--leader-elect=true'
            - '--use-service-account-credentials'
            - '--allocate-node-cidrs=true'
            - '--cluster-cidr=10.244.0.0/16'
            - '--v=2'
          env:
            - name: BINARYLANE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: binarylane-api-token
                  key: api-token
            - name: BINARYLANE_REGION
              value: 'per' # Change to your region
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
