apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarylane-cloud-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: binarylane-cloud-controller-manager
    app.kubernetes.io/component: cloud-controller-manager
    app.kubernetes.io/part-of: kubernetes
spec:
  replicas: 1 # Adjust the number of replicas as needed
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: binarylane-cloud-controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: binarylane-cloud-controller-manager
        app.kubernetes.io/component: cloud-controller-manager
        app.kubernetes.io/part-of: kubernetes
    spec:
      dnsPolicy: Default
      hostNetwork: true
      serviceAccountName: cloud-controller-manager
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: binarylane-cloud-controller-manager
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Exists
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
          operator: Exists
      containers:
        - name: binarylane-cloud-controller-manager
          image: ghcr.io/oscarhermoso/binarylane-cloud-controller-manager:latest
          imagePullPolicy: IfNotPresent
          command:
            - '/binarylane-cloud-controller-manager'
            - '--cloud-provider=binarylane'
            - '--leader-elect=true'
            - '--use-service-account-credentials=true'
            - '--v=2'
          env:
            - name: BINARYLANE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: binarylane-api-token
                  key: api-token
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
