apiVersion: v1
kind: Secret
metadata:
  name: binarylane-api-token
  namespace: kube-system
  labels:
    app.kubernetes.io/name: binarylane-cloud-controller-manager
    app.kubernetes.io/component: cloud-controller-manager
    app.kubernetes.io/part-of: kubernetes
type: Opaque
stringData:
  api-token: 'YOUR_BINARYLANE_API_TOKEN'
